#!/usr/bin/python

# overall TODO:
# add file-modified-times to the history file, if FMTs
# match, don't bother hashing the whole file

import os
import sys
import argparse
import hashlib
import random
import time


def random_hash():
    base = time.time()
    base = base + random.randint(0, sys.maxint)
    return hashlib.sha1(str(base)).hexdigest()


def url_to_scp(url):
    url = url.replace("ssh://", "")
    url = url.replace(".org", ".org:")
    return url


def read_history(filename):
    lines = file(filename).readlines()

    commits = []
    commit = None
    for line in lines:
        if line.strip() == "":
            continue
        k, v = line.strip().split(":", 1)
        if k == "commit":
            if commit:
                commits.append(commit)
            commit = Commit()
            commit.hash = v
            commit.msg = "waffo"
            commit.changes = []
        if not commit:
            continue
        if k == "author":
            commit.author = v
        if k == "date":
            commit.date = v
        if k == "add":
            commit.changes.append(Add(line.strip()))
        if k == "modify":
            commit.changes.append(Modify(line.strip()))
        if k == "delete":
            commit.changes.append(Delete(line.strip()))
    if commit:
        commits.append(commit)

    return commits


def calc_working_tree():
    files = {}
    for commit in read_history(".gut/history"):
        for ch in commit.chs:
            if ch.type == "add":
                files[ch.filename] = File(ch.filename, ch.mode, ch.object)
            if ch.type == "modify":
                files[ch.filename].old_objects.append(files[ch.filename].object)
                files[ch.filename].mode = ch.mode
                files[ch.filename].object = ch.object
            if ch.type == "delete":
                files[ch.filename] = File(ch.filename, "000000", "0" * 40)
    return files


def scp(remote_url, remote_path, local_path):
    #print "scp -q "+remote_url+"/"+remote_path+" "+local_path
    os.system('scp -q "%s/%s" "%s"' % (remote_url, remote_path, local_path))


#######################################################################
# objects

class Commit(object):
    def __init__(self):
        self.author = "auth <moo>"
        self.date = "moo"
        self.msg = "1234"
        self.hash = "1234"
        self.changes = []

    def __str__(self):
        s = ""
        s = s + "commit %s\n" % self.hash
        s = s + "Author: %s\n" % self.author
        s = s + "Date:   %s\n" % self.date
        s = s + "\n"
        s = s + "    %s\n" % self.msg
        s = s + "\n"
        for change in self.changes:
            s = s + str(change) + "\n"
        return s


class Change(object):
    def __init__(self):
        pass


class Add(Change):
    def __init__(self, line):
        self.type, self.filename, self.mode, self.object = line.split(":")

    def __str__(self):
        return ":%s %s %s %s %s  %s" % (
            "000000", self.mode, "0000000...", self.object[0:7] + "...",
            self.type[0].upper(),
            self.filename
        )


class Modify(Change):
    def __init__(self, line):
        self.type, self.filename, self.mode, self.object = line.split(":")

    def __str__(self):
        return ":%s %s %s %s %s  %s" % (
            self.mode, self.mode, self.object[0:7] + "...", self.object[0:7] + "...",
            self.type[0].upper(),
            self.filename
        )


class Delete(Change):
    def __init__(self, line):
        self.type, self.filename = line.split(":")

    def __str__(self):
        return ":%s %s %s %s %s  %s" % (
            "100644", "000000", "1234567...", "0000000...",
            self.type[0].upper(),
            self.filename
        )


class File(object):
    def __init__(self, filename, mode, object):
        self.filename = filename
        self.mode = mode
        self.object = object
        self.old_objects = []


#######################################################################
# commands

def identifier(argv):
    print file(".gut/repo_id").read()


def size(argv):
    os.system("du -cb ./ | grep total | cut -f 1")


def history_size(argv):
    os.system("du -cb ./.gut/ | grep total | cut -f 1")


# TODO list local mods (A, M, ? in git status terms)
# is this used?
def unsynced_file_paths(argv):
    pass


def current_revision(argv):
    print hashlib.sha1(
        file(".gut/history").read() +
        file(".gut/local_history").read()
    ).hexdigest()


def has_remote_changes(argv):
    remote_url = url_to_scp(argv[0])
    scp(remote_url, "history", ".gut/tmp-remote-history")

    local = hashlib.sha1(file(".gut/history").read()).hexdigest()
    remote = hashlib.sha1(file(".gut/tmp-remote-history").read()).hexdigest()

    if local != remote:
        print "true"
        return 0
    else:
        print "false"
        return 1


def has_local_changes(argv):
    files = calc_working_tree()

    for n, wtfilename in enumerate(files):
        f = files[fname]

        if (
            (f.mode == "000000" and os.path.exists(f.filename)) or
            (not os.path.exists(f.filename)) or
            (f.object != hashlib.sha1(file(f.filename).read()).hexdigest()) or
            (os.stat(f.filename)[0] != int(f.mode, 8))
        ):
            print "true"
            return 0

    print "false"
    return 1


# TODO: add & commit
# TODO: push
def sync_up(argv):
    remote_url = url_to_scp(argv[0])

    known_files = calc_working_tree()
    actual_files = {}

    if True:
        print "true"
        return 0
    else:
        print "false"
        return 1


def sync_down(argv):
    remote_url = url_to_scp(argv[0])
    conflicts = False

    print "Downloading history"
    scp(remote_url, "history", ".gut/history")

    print "Processing history"
    files = calc_working_tree()

    for n, wtfilename in enumerate(files):
        print >>sys.stderr, "%d%%" % int(n * 100 / len(files))
        print wtfilename
        wtfile = files[wtfilename]

        if wtfile.mode == "000000":
            if os.path.exists(wtfile.filename):
                os.unlink(wtfile.filename)
        else:
            current_hash = None
            if os.path.exists(wtfile.filename):
                current_hash = hashlib.sha1(file(wtfile.filename).read()).hexdigest()

            if wtfile.object != current_hash:
                if current_hash and current_hash not in wtfile.old_objects:
                    conflicts = True
                    os.rename(wtfile.filename, wtfile.filename+"."+str(time.time()))
                scp(remote_url, "objects/%s/%s" % (wtfile.object[0:2], wtfile.object), wtfile.filename)

            if os.stat(wtfile.filename)[0] != int(wtfile.mode, 8):
                os.chmod(wtfile.filename, int(wtfile.mode, 8))

    if not conflicts:
        print "true"
        return 0
    else:
        print "false"
        return 1


def fetch(argv):
    remote_url = url_to_scp(argv[0])
    target_folder = argv[1]

    if not os.path.exists(target_folder):
        os.mkdir(target_folder)
    if not os.path.exists(target_folder + "/.gut"):
        os.mkdir(target_folder + "/.gut")

    scp(remote_url, "repo_id", target_folder+"/.gut/repo_id")
    file(target_folder+"/.gut/history", "w").write("")
    file(target_folder+"/.gut/local_history", "w").write("")

    os.chdir(target_folder)
    sync_down(argv)


# TODO: limit to last $n
def log(argv):
    #count = argv[0]

    for commit in read_history(".gut/history"):
        print commit


def init(argv):
    # for internal testing only
    if not os.path.exists(argv[1]):
        os.mkdir(argv[1])
    file(argv[1] + "/repo_id", "w").write(random_hash())
    file(argv[1] + "/history", "w").write("")
    if not os.path.exists(argv[1]+"/objects"):
        os.mkdir(argv[1]+"/objects")


def main(argv):
    if len(argv) == 0:
        print "Usage: guts [command]"
        return 1

    if argv[0] == "identifier": return identifier(argv[1:])
    if argv[0] == "size": return size(argv[1:])
    if argv[0] == "history-size": return history_size(argv[1:])
    if argv[0] == "unsynced-file-paths": return unsynced_file_paths(argv[1:])
    if argv[0] == "current-revision": return current_revision(argv[1:])
    if argv[0] == "has-remote-changes": return has_remote_changes(argv[1:])
    if argv[0] == "has-local-changes": return has_local_changes(argv[1:])
    if argv[0] == "sync-up": return sync_up(argv[1:])
    if argv[0] == "sync-down": return sync_down(argv[1:])
    if argv[0] == "fetch": return fetch(argv[1:])
    if argv[0] == "log": return log(argv[1:])
    if argv[0] == "init": return init(argv[1:])


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
