#!/usr/bin/python

# overall TODO:
# add file-modified-times to the history file, if FMTs
# match, don't bother hashing the whole file

import os
import sys
import argparse
import hashlib
import random
import time


def random_hash():
    base = time.time()
    base = base + random.randint(0, sys.maxint)
    return hashlib.sha1(str(base)).hexdigest()


def read_history(filename):
    lines = file(filename).readlines()

    commits = []
    commit = None
    for line in lines:
        if line.strip() == "":
            continue
        k, v = line.strip().split(":", 1)
        if k == "commit":
            if commit:
                commits.append(commit)
            commit = Commit()
            commit.hash = v
            commit.msg = "waffo"
            commit.changes = []
        if not commit:
            continue
        if k == "author":
            commit.author = v
        if k == "date":
            commit.date = v
        if k == "add":
            commit.changes.append(Add(line.strip()))
        if k == "modify":
            commit.changes.append(Modify(line.strip()))
        if k == "delete":
            commit.changes.append(Delete(line.strip()))
    if commit:
        commits.append(commit)

    return commits


def calc_working_tree():
    files = {}
    for commit in read_history(".gut/history"):
        for ch in commit.changes:
            if ch.type == "add":
                files[ch.filename] = File(ch.filename, ch.mode, ch.object)
            if ch.type == "modify":
                files[ch.filename].old_objects.append(files[ch.filename].object)
                files[ch.filename].mode = ch.mode
                files[ch.filename].object = ch.object
            if ch.type == "delete":
                files[ch.filename] = File(ch.filename, "000000", "0" * 40)
    return files


def scp_down(repo_url, repo_path, local_path):
    repo_url = repo_url.replace("ssh://", "")
    repo_url = repo_url.replace(".org", ".org:")
    os.system('scp -q "%s/%s" "%s"' % (repo_url, repo_path, local_path))


def scp_up(repo_url, local_path, repo_path):
    repo_url = repo_url.replace("ssh://", "")
    repo_url = repo_url.replace(".org", ".org:")
    os.system('scp -q "%s" "%s/%s"' % (local_path, repo_url, repo_path))


#######################################################################
# objects

class Commit(object):
    def __init__(self):
        self.author = "auth <moo>"
        self.date = "moo"
        self.msg = "1234"
        self.hash = "1234"
        self.changes = []

    def to_git(self):
        s = ""
        s = s + "commit %s\n" % self.hash
        s = s + "Author: %s\n" % self.author
        s = s + "Date:   %s\n" % self.date
        s = s + "\n"
        s = s + "    %s\n" % self.msg
        s = s + "\n"
        for change in self.changes:
            s = s + change.to_git() + "\n"
        return s

    def to_gut(self):
        s = ""
        s = s + "commit:%s\n" % self.hash
        s = s + "author:%s\n" % self.author
        s = s + "date:%s\n" % self.date
        for change in self.changes:
            s = s + change.to_gut() + "\n"
        return s


class Change(object):
    def __init__(self):
        pass

    def to_gut(self):
        return self.line


class Add(Change):
    def __init__(self, line):
        self.line = line
        self.type, self.filename, self.mode, self.object = line.split(":")

    def to_git(self):
        return ":%s %s %s %s %s  %s" % (
            "000000", self.mode, "0000000...", self.object[0:7] + "...",
            self.type[0].upper(),
            self.filename
        )


class Modify(Change):
    def __init__(self, line):
        self.line = line
        self.type, self.filename, self.mode, self.object = line.split(":")

    def to_git(self):
        return ":%s %s %s %s %s  %s" % (
            self.mode, self.mode, self.object[0:7] + "...", self.object[0:7] + "...",
            self.type[0].upper(),
            self.filename
        )


class Delete(Change):
    def __init__(self, line):
        self.line = line
        self.type, self.filename = line.split(":")

    def to_git(self):
        return ":%s %s %s %s %s  %s" % (
            "100644", "000000", "1234567...", "0000000...",
            self.type[0].upper(),
            self.filename
        )


class File(object):
    def __init__(self, filename, mode, object):
        self.filename = filename
        self.mode = mode
        self.object = object
        self.old_objects = []


#######################################################################
# commands

def identifier(argv):
    print file(".gut/repo_id").read()


def size(argv):
    os.system("du -cb ./ | grep total | cut -f 1")


def history_size(argv):
    os.system("du -cb ./.gut/ | grep total | cut -f 1")


# TODO list local mods (A, M, ? in git status terms)
# is this used?
def unsynced_file_paths(argv):
    pass


def current_revision(argv):
    print hashlib.sha1(file(".gut/history").read()).hexdigest()


def has_remote_changes(argv):
    remote_url = argv[0]
    scp_down(remote_url, "history", ".gut/tmp-remote-history")

    local = hashlib.sha1(file(".gut/history").read()).hexdigest()
    remote = hashlib.sha1(file(".gut/tmp-remote-history").read()).hexdigest()

    if local != remote:
        print "true"
        return 0
    else:
        print "false"
        return 1


def has_local_changes(argv):
    files = calc_working_tree()

    for n, wtfilename in enumerate(files):
        f = files[wtfilename]

        if (
            (f.mode == "000000" and os.path.exists(f.filename)) or
            (f.mode != "000000" and not os.path.exists(f.filename)) or
            (f.mode != "000000" and f.object != hashlib.sha1(file(f.filename).read()).hexdigest()) or
            (f.mode != "000000" and os.stat(f.filename)[0] != int(f.mode, 8))
        ):
            print "true ("+f.filename+")"
            return 0

    print "false"
    return 1


# TODO: add & commit
# TODO: push
def sync_up(argv):
    remote_url = argv[0]

    known_files = calc_working_tree()
    actual_files = {}

    for dirpath, dirnames, filenames in os.walk("."):
        if ".gut" in dirpath:
            continue
        for filename in filenames:
            full_name = os.path.join(dirpath, filename)
            if full_name[0:2] == "./":
                full_name = full_name[2:]
            actual_files[full_name] = File(
                full_name,
                os.stat(full_name)[0],
                hashlib.sha1(file(full_name).read()).hexdigest()
            )

    commit = Commit()
    commit.hash = random_hash() # FIXME: hash(previous commit's hash + changes)
    commit.author = "Shish <shish@shishnet.org>" # FIXME: current user
    commit.date = "2012-02-20 00:00:00 +0100" # FIXME: now
    for f in actual_files:
        if f not in known_files:
            commit.changes.append(Add(":".join([
                "add",
                f,
                "%o" % actual_files[f].mode,
                actual_files[f].object,
            ])))
    for f in known_files:
        if f not in actual_files:
            if known_files[f].mode != "000000":
                commit.changes.append(Delete("delete:"+f))
    for f in known_files:
        if f in actual_files:
            if actual_files[f].object != known_files[f].object:
                commit.changes.append(Delete(":".join([
                    "modify",
                    f,
                    actual_files[f].mode,
                    actual_files[f].object,
                ])))

    if len(commit.changes) == 0:
        print "no changes to sync"
        return 0

    trim = False

    # TODO: lock repo
    for ch in commit.changes:
        if ch.type == "add" or ch.type == "modify":
            scp_up(remote_url, ch.filename, "objects/%s/%s" % (ch.object[0:2], ch.object))
        if ch.type == "modify" or ch.type == "delete":
            if trim:
                pass # FIXME: delete file.old_objects[-1]

    h = file(".gut/history", "a")
    h.write("\n")
    h.write(commit.to_gut())
    h.close()

    scp_up(remote_url, ".gut/history", "history")
    # TODO: unlock repo

    if True:
        print "true"
        return 0
    else:
        print "false"
        return 1


def sync_down(argv):
    remote_url = argv[0]
    conflicts = False

    print "Downloading history"
    scp_down(remote_url, "history", ".gut/history")

    print "Processing history"
    files = calc_working_tree()

    for n, wtfilename in enumerate(files):
        print >>sys.stderr, "%d%%" % int(n * 100 / len(files))
        print wtfilename
        wtfile = files[wtfilename]

        if wtfile.mode == "000000":
            if os.path.exists(wtfile.filename):
                os.unlink(wtfile.filename)
        else:
            current_hash = None
            if os.path.exists(wtfile.filename):
                current_hash = hashlib.sha1(file(wtfile.filename).read()).hexdigest()

            if wtfile.object != current_hash:
                if current_hash and current_hash not in wtfile.old_objects:
                    conflicts = True
                    os.rename(wtfile.filename, wtfile.filename+"."+str(time.time()))
                scp_down(remote_url, "objects/%s/%s" % (wtfile.object[0:2], wtfile.object), wtfile.filename)

            if os.stat(wtfile.filename)[0] != int(wtfile.mode, 8):
                os.chmod(wtfile.filename, int(wtfile.mode, 8))

    if not conflicts:
        print "true"
        return 0
    else:
        print "false"
        return 1


def fetch(argv):
    remote_url = argv[0]
    target_folder = argv[1]

    if not os.path.exists(target_folder):
        os.mkdir(target_folder)
    if not os.path.exists(target_folder + "/.gut"):
        os.mkdir(target_folder + "/.gut")

    scp_down(remote_url, "repo_id", target_folder+"/.gut/repo_id")
    file(target_folder+"/.gut/history", "w").write("")

    os.chdir(target_folder)
    sync_down(argv)


# TODO: limit to last $n
def log(argv):
    #count = argv[0]

    for commit in read_history(".gut/history"):
        print commit.to_git()


def init(argv):
    # for internal testing only
    if not os.path.exists(argv[0]):
        os.mkdir(argv[0])
    file(argv[0] + "/repo_id", "w").write(random_hash())
    file(argv[0] + "/history", "w").write("")
    if not os.path.exists(argv[0]+"/objects"):
        os.mkdir(argv[0]+"/objects")
        for d in ["%02x" %n for n in range(0, 256)]:
            os.mkdir(argv[0]+"/objects/"+d)


def main(argv):
    if len(argv) == 0:
        print "Usage: guts [command]"
        return 1

    if argv[0] == "identifier": return identifier(argv[1:])
    if argv[0] == "size": return size(argv[1:])
    if argv[0] == "history-size": return history_size(argv[1:])
    if argv[0] == "unsynced-file-paths": return unsynced_file_paths(argv[1:])
    if argv[0] == "current-revision": return current_revision(argv[1:])
    if argv[0] == "has-remote-changes": return has_remote_changes(argv[1:])
    if argv[0] == "has-local-changes": return has_local_changes(argv[1:])
    if argv[0] == "sync-up": return sync_up(argv[1:])
    if argv[0] == "sync-down": return sync_down(argv[1:])
    if argv[0] == "fetch": return fetch(argv[1:])
    if argv[0] == "log": return log(argv[1:])
    if argv[0] == "init": return init(argv[1:])


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
